# yaml-language-server: $schema=https://instadeep.aichor.ai/schema/latest/manifest.schema.json

kind: AIchorManifest
apiVersion: 0.2.2

builder:
  image: image
  context: smoke-test # smoke-test folder
  dockerfile: ./build/Dockerfile

spec:
  operator: pytorch
  image: image
  command: "python3 -u main.py --operator=pytorch --sleep=300 --tb-write=True"

  tensorboard:
    enabled: true

  types:
    worker:
      count: 2
      resources:
        cpus: 1
        ramRatio: 2
        shmSizeGB: 0

